export const params = {
  genres: [
    [
      "power metal",
      "metalcore",
      "boomer death metal",
      "djent",
      "deathcore",
      "NAWOHM",
      "black metal",
      "hardcore",
      "thrash",
    ],
    [
      "DnB",
      "house/deep house",
      "glitch hop",
      "disco",
      "neurofunk",
      "late 90's jungle/IDM",
      "dubstep",
    ],
    [
      "rockabilly",
      "nashville chicken pickin'",
      "bro country (luke combs, etc)",
      "country rap",
    ],
    [
      "bossa nova",
      "lounge/muzak",
      "that shit dave weckl be doin",
      "J-fusion",
      "citypop",
    ],
    ["plug type beat", "detroit teejayx6 shit", "90's east coast hip hop"],
  ],
  styleOfs: [
    "a shonen anime theme",
    "nobuo uematsu",
    "tee lopes",
    "zack ordway",
    "michael jackson",
    "cattle decap",
    "spongebob music",
    "snarky puppy",
    "soreption",
    "cocomelon",
    "jun sunuoe",
    "SA2 rouge levels",
    "joeyy",
    "lorna shore",
    "myrone",
    "bulb",
    "protest the hero",
    "toshiki kadomatsu",
    "joshua travis",
    "khublai khan TX",
    "toby fox",
    "fearofdark",
    "stinkbug",
    "chon",
    "car bomb",
    "all that remains",
    "pat metheny group",
    "the dillinger escape plan",
    "killswitch engage",
    "mastodon",
    "epicardiectomy",
    "hans zimmer",
    "young chop on the beat!",
    "the dogshit beats that soulja boy made for I am not a human being 2 by lil wayne",
    "bilmuri",
    "porter robinson",
    "bicflame",
    "new edition",
    "steve reich",
    "pola and bryson",
    "wilderun",
    "pierre sancan",
    "jake bowen",
    "fallujah",
    "allan holdsworth",
    "sam gelliatry",
    "steely dan",
    "casiopea",
    "spite",
    "vildhjarta",
    "dezolve",
    "thundercat",
    "vein.fm",
    "the hallowing of heirdom by winterfylleth",
    "the reign of kindo",
    "varra",
    "abominable putridity",
    "zelliack",
    "the sonic R soundtrack",
    "mitch murder",
    "k suave",
    "kk slider",
    "koji kondo",
  ],
  philosophies: [
    "life gamer",
    "the maxx shit",
    "'twin'",
    "king of beers",
    "gerbil dudaddy",
    "gobal",
    "energic sound ♩",
    "nofap day 492",
    "speedrun your life (KYS ASAP)",
    "the true distruction",
    "i'm in my feels, real ones know (fake friends: don't text me)",
    "schlii",
    '"coffee is makes riff go fast"',
    "xXBonJoviFan420Xx",
    "primitive sound ♩",
    "health sound ♩",
    "silly sound ♩",
    "GOabl sound ♩",
  ],
  modes: [
    "major",
    "dorian",
    "phrygian",
    "lydian",
    "mixolydian",
    "minor",
    "harmonic minor",
    "melodic minor",
  ],
  timeSigs: [
    "3/4",
    "3/4",
    "3/4 triplet feel",
    "3/4 swing feel",
    "4/4",
    "4/4",
    "4/4",
    "4/4",
    "4/4 triplet feel",
    "4/4 swing feel",
    "5/4",
    "6/8",
    "7/8",
    "9/8",
    "11/16",
    "13/16",
    "15/16",
  ],
  constraints: [
    "?nomorethanx",
    "?randomtuning",
    "?ignoreXstrings",
    "use a bitcrusher",
    "use the lick",
    "needs cowbell",
    "needs improv",
    "needs the Bleed rhythm",
    "needs orchestra",
    "needs hybrid picking",
    "needs a section without guitar",
    "transpose an idea up an octave",
    "move an idea through chords diatonically",
    "use modal interchange at least once",
    "use metric modulation at least once",
    "left/right panned call and response",
    "sample - voice memo audio",
    "sample - funny",
    "sample - spotify liked song",
    "sample - something else you've made",
    "no real drums",
    "one takes only",
    "time stretch everything",
    "reverse at least 1 track",
    "guitar intentionally out of tune",
    'intentionally play "wrong" notes',
    "force your mom to listen to it",
    "ask Aviations member for additional constraint",
  ],
  vibes: [
    "floating in the chao garden pool, looking at the clouds",
    "Valley rock-face city festival, and you finally mustered up the courage to hold hands with your crush during the fireworks show at the top of the valley",
    "Underground civic waterworks system for metropolis is failing with large scale corrosion, all high pressure systems, so it doubles as a waterpark (if you can fit in the tubes)",
    'theme song for large fat demon god who wears a big tan trenchcoat and has an "I\'d rather be fishing" shirt (no pants)',
    "Turn up anthem! uh yeaaaaaaaa",
    "The best sandwich that money can buy is at a hoagie shop... at the bottom of the marianas trench",
    "Flashcard song for trivia time in a game that tests whether or not you're predisposed for dimentia (brain age 3: the regression)",
    "Balinese, Maritius, Indonesian gamelan players all come to battle to see who have best gamelon",
    "The fight theme that played when Jair Bolsonario got attacked by that Emu",
    "Post-Baltic Far right ethnostate music",
    'a song called "soulfracked"',
    "soundtrack for a video of nicocadoavacado eating gravel",
    "the feeling of MW2 (2009) split screen Knife wars on Rust",
    "coffee on an empty stomach",
    'Getting in a fight with the owner of the bowling alley cause he won\'t let you play as "Jizzy Gillespe"',
    "Panic attack in an Arby's",
    "The bi-annual cloud festival where you and all the others race your handbuilt cloud cars. You're gonna win it this time, you can feel it.",
    "Accidently clipping through the geometry of the simulation and falling into the earth's core",
    "Dripped out in the freshest designer clothes but you spilled buffalo wild wings asian zing (tm) on it",
    "Giant mech walking through the ocean that got its foot stuck in a really deep hole",
    "We finally built an oil pipeline to the peak of the tallest mountain in the wordl!",
    "Fat People falling compilation on Youtube (2008)",
    "That one day that Evan Stanley said that an egirl simp doxxed him",
    "The song that was playing in Drake's head when he posted Hentai to his instagram story",
  ],
};

export const images = [
  'url("./assets/img/compchallenge/bananas.png")',
  'url("./assets/img/compchallenge/beige-tiles.png")',
  'url("./assets/img/compchallenge/christmas-black.png")',
  'url("./assets/img/compchallenge/cork-board.png")',
  'url("./assets/img/compchallenge/halftone-yellow.png")',
  'url("./assets/img/compchallenge/leaves.png")',
  'url("./assets/img/compchallenge/paisley.png")',
  'url("./assets/img/compchallenge/wheat.png")',
  'url("./assets/img/compchallenge/moroccan-flower-dark.png")',
];

export const sounds = [
  "./assets/audio/kidpix/i made a booboo.wav",
  "./assets/audio/kidpix/no no no.wav",
  "./assets/audio/kidpix/no way.wav",
  "./assets/audio/kidpix/now wait a minute.wav",
  "./assets/audio/kidpix/nuh uh.wav",
  "./assets/audio/kidpix/oh no.wav",
  "./assets/audio/kidpix/oops.wav",
  "./assets/audio/kidpix/oops2.wav",
  "./assets/audio/kidpix/uh oh.wav",
  "./assets/audio/kidpix/uhoh.wav",
  "./assets/audio/kidpix/undo undo.wav",
  "./assets/audio/kidpix/wait a minute.wav",
  "./assets/audio/kidpix/yikes.wav",
  "./assets/audio/kidpix/you dont want it.wav",
  "./assets/audio/kidpix/yuck.wav",
];
